// Code generated by "stringer -type TokenType"; DO NOT EDIT.

package scanner

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NONE-0]
	_ = x[COMMA-1]
	_ = x[LEFT_PAREN-2]
	_ = x[RIGHT_PAREN-3]
	_ = x[DOT-4]
	_ = x[MINUS-5]
	_ = x[PLUS-6]
	_ = x[STAR-7]
	_ = x[SLASH-8]
	_ = x[SEMICOLON-9]
	_ = x[BANG-10]
	_ = x[BANG_EQUAL-11]
	_ = x[EQUAL-12]
	_ = x[EQUAL_EQUAL-13]
	_ = x[GREATER-14]
	_ = x[GREATER_EQUAL-15]
	_ = x[LESS-16]
	_ = x[LESS_EQUAL-17]
	_ = x[IDENTIFIER-18]
	_ = x[STRING-19]
	_ = x[NUMBER-20]
	_ = x[TYPE-21]
	_ = x[SELECT-22]
	_ = x[INSERT-23]
	_ = x[INTO-24]
	_ = x[UPDATE-25]
	_ = x[DELETE-26]
	_ = x[CREATE-27]
	_ = x[FROM-28]
	_ = x[WHERE-29]
	_ = x[GROUP-30]
	_ = x[OFFSET-31]
	_ = x[ORDER-32]
	_ = x[LIMIT-33]
	_ = x[SET-34]
	_ = x[AND-35]
	_ = x[OR-36]
	_ = x[NOT-37]
	_ = x[VALUES-38]
}

const _TokenType_name = "NONECOMMALEFT_PARENRIGHT_PARENDOTMINUSPLUSSTARSLASHSEMICOLONBANGBANG_EQUALEQUALEQUAL_EQUALGREATERGREATER_EQUALLESSLESS_EQUALIDENTIFIERSTRINGNUMBERTYPESELECTINSERTINTOUPDATEDELETECREATEFROMWHEREGROUPOFFSETORDERLIMITSETANDORNOTVALUES"

var _TokenType_index = [...]uint8{0, 4, 9, 19, 30, 33, 38, 42, 46, 51, 60, 64, 74, 79, 90, 97, 110, 114, 124, 134, 140, 146, 150, 156, 162, 166, 172, 178, 184, 188, 193, 198, 204, 209, 214, 217, 220, 222, 225, 231}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
