// Code generated by "stringer -type TokenType"; DO NOT EDIT.

package scanner

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NONE-0]
	_ = x[COMMA-1]
	_ = x[LEFT_PAREN-2]
	_ = x[RIGHT_PAREN-3]
	_ = x[DOT-4]
	_ = x[MINUS-5]
	_ = x[PLUS-6]
	_ = x[STAR-7]
	_ = x[SLASH-8]
	_ = x[SEMICOLON-9]
	_ = x[BANG-10]
	_ = x[BANG_EQUAL-11]
	_ = x[EQUAL-12]
	_ = x[EQUAL_EQUAL-13]
	_ = x[GREATER-14]
	_ = x[GREATER_EQUAL-15]
	_ = x[LESS-16]
	_ = x[LESS_EQUAL-17]
	_ = x[IDENTIFIER-18]
	_ = x[STRING-19]
	_ = x[NUMBER-20]
	_ = x[DATATYPE_BOOLEAN-21]
	_ = x[DATATYPE_STRING-22]
	_ = x[DATATYPE_NUMBER-23]
	_ = x[SELECT-24]
	_ = x[INSERT-25]
	_ = x[INTO-26]
	_ = x[UPDATE-27]
	_ = x[DELETE-28]
	_ = x[CREATE-29]
	_ = x[TABLE-30]
	_ = x[FROM-31]
	_ = x[WHERE-32]
	_ = x[GROUP-33]
	_ = x[OFFSET-34]
	_ = x[ORDER-35]
	_ = x[LIMIT-36]
	_ = x[SET-37]
	_ = x[AND-38]
	_ = x[OR-39]
	_ = x[NOT-40]
	_ = x[VALUES-41]
}

const _TokenType_name = "NONECOMMALEFT_PARENRIGHT_PARENDOTMINUSPLUSSTARSLASHSEMICOLONBANGBANG_EQUALEQUALEQUAL_EQUALGREATERGREATER_EQUALLESSLESS_EQUALIDENTIFIERSTRINGNUMBERDATATYPE_BOOLEANDATATYPE_STRINGDATATYPE_NUMBERSELECTINSERTINTOUPDATEDELETECREATETABLEFROMWHEREGROUPOFFSETORDERLIMITSETANDORNOTVALUES"

var _TokenType_index = [...]uint16{0, 4, 9, 19, 30, 33, 38, 42, 46, 51, 60, 64, 74, 79, 90, 97, 110, 114, 124, 134, 140, 146, 162, 177, 192, 198, 204, 208, 214, 220, 226, 231, 235, 240, 245, 251, 256, 261, 264, 267, 269, 272, 278}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
